apiVersion: crd.projectcalico.org/v1
kind: FelixConfiguration
metadata:
  name: default
spec:
  bpfLogLevel: ""
  ipipEnabled: true
  logSeverityScreen: Info
  reportingInterval: 0s
  vxlanEnabled: false
  wireguardEnabled: false
  wireguardInterfaceName: wireguard_cali
