apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    fluid: "true"
    category: system
  annotations:
    fluidhq.io/display: "false"
  name: meta-apps
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: .meta-apps
    repoURL: "https://github.com/aseitnetworks/fluid-k8s-apps"
    targetRevision: BRANCHREPLACEMENT
  syncPolicy:
    automated:
      selfHeal: true
