apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    email: support@mongodb.com
  labels:
    owner: mongodb
  name: mongodb-kubernetes-operator
spec:
  template:
    spec:
      containers:
        - env:
            - $patch: delete
              name: WATCH_NAMESPACE
          name: mongodb-kubernetes-operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    email: support@mongodb.com
  labels:
    owner: mongodb
  name: mongodb-kubernetes-operator
spec:
  template:
    spec:
      containers:
        - env:
            - name: WATCH_NAMESPACE
              value: "*"
          name: mongodb-kubernetes-operator
