apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: kube-httpproxy
  namespace: default
spec:
  virtualhost:
    fqdn: kubernetes.svc
    tls:
      passthrough: true
  tcpproxy:
    services:
      - name: kubernetes
        port: 443
  routes:
    - permitInsecure: true
      services:
        - name: kubernetes
          port: 443
          protocol: tls
      conditions:
        - prefix: /
