apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
spec:
  serviceName: mongo
  selector:
    matchLabels:
      app: mongo
      unit: app
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo
        unit: app
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongo
          image: mongo:5
          imagePullPolicy: Always
          command:
            - mongod
            # - "--replSet"
            # - rs0
            - "--bind_ip"
            - 0.0.0.0
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
              readOnly: false
        # - name: mongo-sidecar
        #   image: cvallance/mongo-k8s-sidecar
        #   imagePullPolicy: Always
        #   env:
        #     - name: MONGO_SIDECAR_POD_LABELS
        #       value: "app=mongo,unit=app"
  volumeClaimTemplates:
    - metadata:
        name: mongo-data
        namespace: fluid-system
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
