apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vms.fluidhq.io:vnc
rules:
  - apiGroups:
      - subresources.kubevirt.io
    resources:
      - virtualmachineinstances/vnc
    verbs:
      - get
