apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fluid-vnc-binding
subjects:
  - kind: ServiceAccount
    name: fluid-vnc
    namespace: fluid-system
roleRef:
  kind: ClusterRole
  name: vms.fluidhq.io:vnc
  apiGroup: rbac.authorization.k8s.io
