apiVersion: v1
kind: Service
metadata:
  name: fluid-maestro
  namespace: fluid-system
spec:
  type: ClusterIP
  selector:
    app: fluid-maestro
  ports:
    - protocol: TCP
      port: 4000
      name: http
      targetPort: 4000
    - protocol: TCP
      port: 4001
      name: special
      targetPort: 4001
