apiVersion: v1
kind: LimitRange
metadata:
  name: default-limitrange
  namespace: projectcontour
spec:
  limits:
    - default:
        cpu: 500m
        memory: 512Mi
      defaultRequest:
        cpu: 10m
        memory: 64Mi
      max:
        cpu: 1000m
        memory: 512Mi
      type: Container
