apiVersion: v1
kind: LimitRange
metadata:
  name: default-limitrange
  namespace: metallb-system
spec:
  limits:
    - default:
        cpu: 250m
        memory: 256Mi
      defaultRequest:
        cpu: 10m
        memory: 32Mi
      max:
        cpu: 250m
        memory: 256Mi
      type: Container
