apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    fluid: "true"
    category: system
  annotations:
    fluidhq.io/display: "Cilium CNI"
  name: cilium
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values.yaml
    path: cni/cilium
    repoURL: https://github.com/aseitnetworks/fluid-k8s-apps.git
    targetRevision: BRANCHREPLACEMENT
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
