apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    fluid: "true"
    category: system
  annotations:
    fluidhq.io/display: "Nested Cluster Datastore Operator"
  name: cockroach-operator
  namespace: argocd
spec:
  destination:
    namespace: cockroach-operator-system
    server: https://kubernetes.default.svc
  project: default
  source:
    path: cockroach-operator
    repoURL: "https://github.com/Fluid-Labs-Pty-Ltd/fluid-k8s-apps"
    targetRevision: BRANCHREPLACEMENT
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
