apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    fluid: "true"
    category: system
  annotations:
    fluidhq.io/display: "Virtualization"
  name: kubevirt
  namespace: argocd
spec:
  destination:
    namespace: kubevirt
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kubevirt
    repoURL: "https://github.com/aseitnetworks/fluid-k8s-apps"
    targetRevision: BRANCHREPLACEMENT
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: cdis.cdi.kubevirt.io
      jsonPointers:
        - /spec/versions
