apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    fluid: "true"
    display: "Network VPC Support"
    category: system
  name: cluster-network-addons
  namespace: argocd
spec:
  destination:
    namespace: cluster-network-addons
    server: https://kubernetes.default.svc
  project: default
  source:
    path: cluster-network-addons
    repoURL: "https://github.com/aseitnetworks/fluid-k8s-apps"
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
