apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    fluid: "true"
    category: system
  annotations:
    fluidhq.io/display: "Fluid Tunnel"
  name: fluid-tunnel
  namespace: argocd
spec:
  destination:
    namespace: fluid-tunnel
    server: https://kubernetes.default.svc
  project: default
  source:
    path: fluid-tunnel
    repoURL: "https://github.com/aseitnetworks/fluid-k8s-apps"
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
