apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    fluid: "true"
    category: system
  annotations:
    fluidhq.io/display: "false"
  name: kube-ingress
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kube-ingress
    repoURL: "https://github.com/aseitnetworks/fluid-k8s-apps"
    targetRevision: BRANCHREPLACEMENT
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
