apiVersion: v2
name: Cilium
description: A Helm chart for Cilium
type: application
version: 1.13.18
appVersion: "1.13.18"

dependencies:
  - name: cilium
    version: 1.13.18
    repository: https://helm.cilium.io/