name: fluid-k8s-apps

on:
  push:
    branches: [master]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: azure/setup-kubectl@v3
      - uses: azure/setup-helm@v3

      - name: Install AWSCLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip -q awscliv2.zip
          sudo ./aws/install --update

      - name: Configure AWS
        run: |
          aws configure --profile flow <<-EOF > /dev/null 2>&1
          ${{ secrets.AWS_ACCESS_KEY_ID }}
          ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          ap-southeast-2
          text
          EOF

      - name: Build Kube Manifest
        run: |
          HOME=`pwd`
          mkdir -p $HOME/artifacts/
          kubectl version --client=true

          kubectl kustomize $HOME/argocd > $HOME/artifacts/argocd.yaml
          kubectl kustomize $HOME/longhorn > $HOME/artifacts/longhorn.yaml
          kubectl kustomize $HOME/cni/calico > $HOME/artifacts/calico.yaml
          
          cp $HOME/self.yaml $HOME/artifacts/
          cp $HOME/.meta-apps/calico.yaml $HOME/artifacts/calico-app.yaml
          cp $HOME/.meta-apps/cilium.yaml $HOME/artifacts/cilium-app.yaml

          cd $HOME/cni/cilium/
          helm dependency build
          helm template . -f values.yaml -n kube-system > $HOME/artifacts/cilium.yaml

          find $HOME/artifacts -type f -exec sed -i 's/BRANCHREPLACEMENT/${{ github.ref_name }}/g' {} +

      - name: Sync to S3
        run: |
          aws s3 sync ${{ env.SOURCE_DIR }} s3://${{ env.AWS_S3_BUCKET }}/${{ env.DEST_DIR }}/${{ github.ref_name }} --profile flow --acl public-read --follow-symlinks
        env:
          AWS_S3_BUCKET: fluid-artifacts
          SOURCE_DIR: artifacts
          DEST_DIR: fluid-kube
