name: fluid-k8s-apps

on:
  push:
    branches: [master, production, dev]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    
    permissions:
      contents: 'read'
      id-token: 'write'
    
    steps:
      - uses: actions/checkout@v3

      - uses: azure/setup-kubectl@v3
      - uses: azure/setup-helm@v3
      
      - name: 'authenticate GCP'
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: ${{secrets.GCP_PROJECT_NAME}}
          workload_identity_provider: ${{secrets.GCP_WORKLOAD_PROVIDER}}

      - name: 'Set Up gcloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: '>= 363.0.0'   



      - name: Build Kube Manifest
        run: |
          HOME=`pwd`
          mkdir -p $HOME/artifacts/
          kubectl version --client=true

          kubectl kustomize $HOME/.argo-apps > $HOME/artifacts/argo-apps.yaml
          kubectl kustomize $HOME/argocd > $HOME/artifacts/argocd.yaml
          kubectl kustomize $HOME/longhorn > $HOME/artifacts/longhorn.yaml
          kubectl kustomize $HOME/cni/calico > $HOME/artifacts/calico.yaml

          mkdir -p $HOME/artifacts/apps
          cp $HOME/.argo-apps/*.yaml $HOME/artifacts/apps/

          cd $HOME/cni/cilium/
          helm dependency build
          helm template . -f values.yaml -n kube-system > $HOME/artifacts/cilium.yaml

          find $HOME/artifacts -type f -exec sed -i 's/BRANCHREPLACEMENT/${{ github.ref_name }}/g' {} +
          find $HOME/artifacts/apps -type f -exec sed -i 's/BRANCHREPLACEMENT/${{ github.ref_name }}/g' {} +

      - name: Sync to GCS
        run: |
          gcloud storage rsync ${{ env.SOURCE_DIR }} gs://${{ env.GCS_BUCKET }}/${{ env.DEST_DIR }}/${{ github.ref_name }} --recursive --no-ignore-symlinks
        env:
          GCS_BUCKET: artifacts.fluidhq.io
          SOURCE_DIR: artifacts
          DEST_DIR: fluid-kube
