apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluid-etcd-backup-operator-snapshots
rules:
  - apiGroups: ["k3s.cattle.io"]
    resources: ["etcdsnapshotfiles"]
    verbs: ["get", "list", "watch", "patch"]
