apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluid-etcd-backup-operator
  labels:
    app: fluid-etcd-backup-operator
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: fluid-etcd-backup-operator
  template:
    metadata:
      labels:
        app: fluid-etcd-backup-operator
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
        runAsUser: 65535
        runAsGroup: 65535
        fsGroup: 65535
      containers:
        - name: fluid-etcd-backup-operator
          image: australia-southeast2-docker.pkg.dev/fluidhq/public/fluid-etcd-backup-operator:v0.0.1
          imagePullPolicy: IfNotPresent
          env:
            - name: RUST_LOG
              value: info
            - name: NAMESPACE
              value: fluid-system
            - name: UPLOAD_IMAGE_REPOSITORY
              value: australia-southeast2-docker.pkg.dev/fluidhq/public/fluid-etcd-upload-job
            - name: UPLOAD_IMAGE_TAG
              value: v0.0.1
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            privileged: false
            capabilities:
              drop: ["ALL"]
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
      hostIPC: false
      hostNetwork: false
      hostPID: false
      serviceAccountName: fluid-etcd-backup-operator
      automountServiceAccountToken: true
