apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - fluid-etcd-backup-crd.yaml
  - fluid-etcd-backup-serviceaccount.yaml
  - fluid-etcd-backup-deployment.yaml
  - fluid-etcd-backup-clusterrole.yaml
  - fluid-etcd-backup-clusterrolebinding.yaml
  - fluid-etcd-backup-role.yaml
  - fluid-etcd-backup-rolebinding.yaml
